common:
    lid_topic:  "/3/livox/lidar" 
    imu_topic:  "/3/livox/imu" 
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 3                # 3 for OUST64 
    scan_line: 4
    blind: 0.01                 # 遮挡区域设置，单位：米

mapping:
    acc_cov: 0.1                 
    gyr_cov: 0.1                 
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    360
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    
    extrinsic_T: [ 0.0, 0.0, 0.0 ]
    extrinsic_R: [ 1,  0,  0,
                   0,  1,  0,
                   0,  0,  1]

publish:
    path_en: true                       # 启用路径（用于可视化）
    scan_publish_en: true               # 发布点云
    dense_publish_en: false             # 关闭稠密点云
    scan_bodyframe_pub_en: true        # 关闭body系点云

pcd_save:
    pcd_save_en: false                  # 关闭点云保存
    interval: -1

# publish:
#     path_en:  false
#     scan_publish_en:  true       # false: close all the point cloud output
#     dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
#     scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

# pcd_save:
#     pcd_save_en: true
#     interval: -1                 # how many LiDAR frames saved in each pcd file; 
#                                  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
